# Form implementation generated from reading ui file 'remote.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 30, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.power = QtWidgets.QPushButton(parent=self.centralwidget)
        self.power.setGeometry(QtCore.QRect(90, 290, 113, 32))
        self.power.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/power.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.power.setIcon(icon)
        self.power.setObjectName("power")
        self.mute = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mute.setGeometry(QtCore.QRect(90, 380, 113, 32))
        self.mute.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/mute.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.mute.setIcon(icon1)
        self.mute.setObjectName("mute")
        self.cDN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cDN.setGeometry(QtCore.QRect(0, 380, 81, 32))
        self.cDN.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/Down Arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cDN.setIcon(icon2)
        self.cDN.setObjectName("cDN")
        self.cUP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cUP.setGeometry(QtCore.QRect(0, 290, 81, 32))
        self.cUP.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/Up Arrow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cUP.setIcon(icon3)
        self.cUP.setObjectName("cUP")
        self.vUP = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vUP.setGeometry(QtCore.QRect(210, 290, 81, 32))
        self.vUP.setText("")
        self.vUP.setIcon(icon3)
        self.vUP.setObjectName("vUP")
        self.vDN = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vDN.setGeometry(QtCore.QRect(210, 380, 81, 32))
        self.vDN.setText("")
        self.vDN.setIcon(icon2)
        self.vDN.setObjectName("vDN")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 36))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RemoteController"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
